# low to high resolution

In [1]:
import os
import numpy as np
import pandas as pd
from joblib import dump, load
from osgeo import gdal
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score
from image import read_image, create_image

SEED = 42

## sentinel, 10 meters resolution, blue, green, red, VNIR bands

In [35]:
img_dir = "data/images/high_resolution/SENTINEL-2B_MSI_20210511_084252/"
bands_filenames = [
    "SENTINEL-2B_MSI_20210511_084252_channel2_1.tif",
    "SENTINEL-2B_MSI_20210511_084252_channel3_1.tif",
    "SENTINEL-2B_MSI_20210511_084252_channel4_1.tif",
    "SENTINEL-2B_MSI_20210511_084252_channel8_1.tif",
]
bands_names = ["Blue", "Green", "Red", "VNIR"]
data_path = "data/SENTINEL-2B_MSI_20210511_084252_Blue_Red_Green_VNIR.csv"

### extracting table data from image

In [3]:
%%time

data = pd.DataFrame(columns=bands_names)
for band_name, band_filename in zip(bands_names, bands_filenames):
    band_path = os.path.join(img_dir, band_filename)
    data[band_name] = read_image(band_path)

CPU times: total: 41.2 s
Wall time: 4min 17s


In [4]:
data

Blue  Green  Red  VNIR
0           998    750  605   654
1          1008    746  612   682
2          1008    758  612   699
3          1016    748  610   703
4          1022    765  603   717
...         ...    ...  ...   ...
120560395   837    628  496   376
120560396   823    634  496   395
120560397   819    628  495   399
120560398   827    626  490   440
120560399   837    639  510   490

[120560400 rows x 4 columns]

In [5]:
%%time

data.to_csv(data_path, index=False)

CPU times: total: 3min
Wall time: 3min 35s


### kmeans, 20 clusters


In [6]:
kmeans_backup_path = "data/backups/SENTINEL-2B_MSI_20210511_084252_kmeans_20_clusters_trained_on_Blue_Red_Green_VNIR.joblib"
labels_path = "data/SENTINEL-2B_MSI_20210511_084252_kmeans_20_clusters_labels_trained_on_Blue_Red_Green_VNIR.csv"
sample_img_path = os.path.join(img_dir, bands_filenames[0])
result_img_path = "data/images/high_resolution/results/SENTINEL-2B_MSI_20210511_084252_kmeans_20_clusters_labels_trained_on_Blue_Red_Green_VNIR.tif"

In [3]:
%%time

data = pd.read_csv(data_path, index_col=False)

CPU times: total: 59.1 s
Wall time: 1min 9s


In [4]:
data

Blue  Green  Red  VNIR
0           998    750  605   654
1          1008    746  612   682
2          1008    758  612   699
3          1016    748  610   703
4          1022    765  603   717
...         ...    ...  ...   ...
120560395   837    628  496   376
120560396   823    634  496   395
120560397   819    628  495   399
120560398   827    626  490   440
120560399   837    639  510   490

[120560400 rows x 4 columns]

In [5]:
%%time

kmeans = KMeans(n_clusters=20, random_state=SEED).fit(data)

CPU times: total: 5h 19min 57s
Wall time: 5h 16min 55s


In [12]:
%%time

dump(kmeans, kmeans_backup_path)

CPU times: total: 453 ms
Wall time: 514 ms


['data/backups/SENTINEL-2B_MSI_20210511_084252_kmeans_trained_on_Blue_Red_Green_VNIR.joblib']

In [10]:
%%time

kmeans_20 = load(kmeans_backup_path)

CPU times: user 222 ms, sys: 510 ms, total: 732 ms
Wall time: 729 ms


In [8]:
kmeans_labels = pd.Series(kmeans.labels_)

In [9]:
kmeans_labels

0            3
1            3
2            3
3            3
4            3
            ..
120560395    9
120560396    9
120560397    9
120560398    9
120560399    9
Length: 120560400, dtype: int32

In [10]:
%%time

kmeans_labels.to_csv(labels_path, index=False)

CPU times: total: 1min 59s
Wall time: 2min 4s


In [11]:
%%time

kmeans_20_labels = pd.read_csv(labels_path, index_col=False)

CPU times: user 10.7 s, sys: 3.29 s, total: 14 s
Wall time: 14.1 s


In [4]:
%%time

kmeans_labels = np.array(kmeans_labels).ravel()

CPU times: total: 344 ms
Wall time: 361 ms


In [14]:
%%time

kmeans_labels, np.unique(kmeans_labels)

CPU times: total: 3.41 s
Wall time: 3.65 s


(array([3, 3, 3, ..., 9, 9, 9], dtype=int64),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19], dtype=int64))

In [7]:
%%time

create_image(sample_img_path, result_img_path, kmeans_labels)

CPU times: total: 45.5 s
Wall time: 47.1 s


### kmeans, 10 clusters

In [14]:
kmeans_backup_path = "data/backups/SENTINEL-2B_MSI_20210511_084252_kmeans_10_clusters_trained_on_Blue_Red_Green_VNIR.joblib"
labels_path = "data/SENTINEL-2B_MSI_20210511_084252_kmeans_10_clusters_labels_trained_on_Blue_Red_Green_VNIR.csv"
sample_img_path = os.path.join(img_dir, bands_filenames[0])
result_img_path = "data/images/high_resolution/results/SENTINEL-2B_MSI_20210511_084252_kmeans_10_clusters_labels_trained_on_Blue_Red_Green_VNIR.tif"

In [23]:
%%time

data = pd.read_csv(data_path, index_col=False)

CPU times: user 41 s, sys: 22.3 s, total: 1min 3s
Wall time: 1min 4s


In [9]:
data

Blue  Green  Red  VNIR
0           998    750  605   654
1          1008    746  612   682
2          1008    758  612   699
3          1016    748  610   703
4          1022    765  603   717
...         ...    ...  ...   ...
120560395   837    628  496   376
120560396   823    634  496   395
120560397   819    628  495   399
120560398   827    626  490   440
120560399   837    639  510   490

[120560400 rows x 4 columns]

In [10]:
%%time

kmeans = KMeans(n_clusters=10, random_state=SEED).fit(data)

CPU times: user 3h 30min 44s, sys: 9h 8min, total: 12h 38min 45s
Wall time: 28min 2s


In [7]:
%%time

dump(kmeans, kmeans_backup_path)

CPU times: total: 547 ms
Wall time: 2.94 s


['data/backups/SENTINEL-2B_MSI_20210511_084252_kmeans_10_clusters_trained_on_Blue_Red_Green_VNIR.joblib']

In [15]:
%%time

kmeans_10 = load(kmeans_backup_path)

CPU times: user 215 ms, sys: 1.05 s, total: 1.27 s
Wall time: 1.26 s


In [8]:
kmeans_labels = pd.Series(kmeans.labels_)

In [9]:
kmeans_labels

0            0
1            0
2            0
3            0
4            0
            ..
120560395    0
120560396    0
120560397    0
120560398    0
120560399    0
Length: 120560400, dtype: int32

In [10]:
%%time

kmeans_labels.to_csv(labels_path, index=False)

CPU times: total: 1min 45s
Wall time: 1min 47s


In [16]:
%%time

kmeans_10_labels = pd.read_csv(labels_path, index_col=False)

CPU times: user 8.85 s, sys: 3.94 s, total: 12.8 s
Wall time: 13 s


In [5]:
%%time

kmeans_labels = np.array(kmeans_labels).ravel()

CPU times: total: 562 ms
Wall time: 600 ms


In [6]:
%%time

kmeans_labels, np.unique(kmeans_labels)

CPU times: total: 4.16 s
Wall time: 4.44 s


(array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

In [15]:
%%time

create_image(sample_img_path, result_img_path, kmeans_labels)

CPU times: total: 55.5 s
Wall time: 1min 2s


### metrics

In [29]:
kmeans_20_labels = kmeans_20_labels.values.ravel()
kmeans_10_labels = kmeans_10_labels.values.ravel()

In [30]:
print(kmeans_20.inertia_)
print(kmeans_10.inertia_)

3422984021885.875
6534904673580.018


In [33]:
%%time

silhouette_coef_kmeans_20 = silhouette_score(data, kmeans_20_labels, metric='euclidean')

KeyboardInterrupt: 

In [ ]:
%%time

silhouette_coef_kmeans_10 = silhouette_score(data, kmeans_10_labels, metric='euclidean')

In [ ]:
print(silhouette_coef_kmeans_20)
print(silhouette_coef_kmeans_10)

In [ ]:
%%time

calinski_harabasz_index_kmeans_20 = calinski_harabasz_score(data, kmeans_20_labels)

In [ ]:
%%time

calinski_harabasz_index_kmeans_10 = calinski_harabasz_score(data, kmeans_10_labels)

In [ ]:
print(calinski_harabasz_index_kmeans_20)
print(calinski_harabasz_index_kmeans_10)

In [ ]:
%%time

davies_bouldin_index_kmeans_20 = davies_bouldin_score(data, kmeans_20_labels)

In [ ]:
%%time

davies_bouldin_index_kmeans_10 = davies_bouldin_score(data, kmeans_10_labels)

In [ ]:
print(davies_bouldin_index_kmeans_20)
print(davies_bouldin_index_kmeans_10)

### gaussian mixture

### segmentation

## MODIS data vs. Sentinel data

In [2]:
modis_img_path = "data/images/low_resolution/lccswm2010_4.img"
modis_reprojected_img_path = "data/images/low_resolution/lccswm2010_4_reprojected.img"
sentinel_img_path = "data/images/high_resolution/SENTINEL-2B_MSI_20210511_084252/SENTINEL-2B_MSI_20210511_084252_channel2_1.tif"

### MODIS data reprojection

In [5]:
%%time

modis_img = gdal.Open(modis_img_path, gdal.GA_ReadOnly)
sentinel_img = gdal.Open(sentinel_img_path, gdal.GA_ReadOnly)

CPU times: user 7.85 ms, sys: 0 ns, total: 7.85 ms
Wall time: 3.3 ms


In [47]:
modis_img.GetProjection()  # Albers Conical Equal Area

'PROJCS["Albers Conical Equal Area",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Albers_Conic_Equal_Area"],PARAMETER["latitude_of_center",56],PARAMETER["longitude_of_center",100],PARAMETER["standard_parallel_1",50],PARAMETER["standard_parallel_2",70],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'

In [48]:
sentinel_img.GetProjection()  # EPSG:32637

'PROJCS["WGS 84 / UTM zone 37N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",39],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32637"]]'

In [49]:
%%time

warp = gdal.Warp(modis_reprojected_img_path, modis_img, dstSRS='EPSG:32637')
warp = None

CPU times: user 6min 55s, sys: 3.19 s, total: 6min 58s
Wall time: 6min 59s


### Territory selection from MODIS data

In [6]:
%%time

modis_img = gdal.Open(modis_reprojected_img_path, gdal.GA_ReadOnly)

CPU times: user 11.2 ms, sys: 0 ns, total: 11.2 ms
Wall time: 8.71 ms


In [7]:
sentinel_geotransform = sentinel_img.GetGeoTransform()
sentinel_x_size = sentinel_img.RasterXSize
sentinel_y_size = sentinel_img.RasterYSize
sentinel_top_left_x = sentinel_geotransform[0]
sentinel_top_left_y = sentinel_geotransform[3]
sentinel_pixel_width = sentinel_geotransform[1]
sentinel_pixel_height = sentinel_geotransform[5]
sentinel_rotation_1 = sentinel_geotransform[2]
sentinel_rotation_2 = sentinel_geotransform[4]

sentinel_x_size, sentinel_y_size, sentinel_top_left_x, sentinel_top_left_y, sentinel_pixel_width, sentinel_pixel_height, sentinel_rotation_1, sentinel_rotation_2

(10980, 10980, 399960.0, 6300000.0, 10.0, -10.0, 0.0, 0.0)

In [8]:
modis_geotransform = modis_img.GetGeoTransform()
modis_x_size = modis_img.RasterXSize
modis_y_size = modis_img.RasterYSize
modis_top_left_x = modis_geotransform[0]
modis_top_left_y = modis_geotransform[3]
modis_pixel_width = modis_geotransform[1]
modis_pixel_height = modis_geotransform[5]
modis_rotation_1 = modis_geotransform[2]
modis_rotation_2 = modis_geotransform[4]

modis_x_size, modis_y_size, modis_top_left_x, modis_top_left_y, modis_pixel_width, modis_pixel_height, modis_rotation_1, modis_rotation_2

(42126,
 40936,
 -2867271.7564270175,
 13202206.94775594,
 275.2262822576454,
 -275.2262822576454,
 0.0,
 0.0)

In [9]:
sentinel_bottom_right_x = sentinel_top_left_x + sentinel_x_size * sentinel_pixel_width
sentinel_bottom_right_y = sentinel_top_left_y + sentinel_y_size * sentinel_pixel_height
sentinel_bottom_right_x, sentinel_bottom_right_y

(509760.0, 6190200.0)

In [15]:
x = sentinel_bottom_right_x - sentinel_top_left_x
y = sentinel_bottom_right_y - sentinel_top_left_y
x / modis_pixel_width, y / modis_pixel_height



(398.94445799043933, 398.94445799043933)

In [20]:
modis_selected_data_x_size = round(sentinel_x_size * sentinel_pixel_width / modis_pixel_width)
modis_selected_data_y_size = round(sentinel_y_size * sentinel_pixel_height / modis_pixel_height)
modis_selected_data_x_size, modis_selected_data_y_size

(399, 399)

In [21]:
x, y = sentinel_top_left_x, sentinel_top_left_y
modis_x_offset = int((x - modis_top_left_x) / modis_pixel_width)
modis_y_offset = int((y - modis_top_left_y) / modis_pixel_height)
modis_x_offset, modis_y_offset

(11871, 25078)

In [22]:
%%time

band = modis_img.GetRasterBand(1)
selected_modis_data = band.ReadAsArray(modis_x_offset, modis_y_offset, modis_selected_data_x_size, modis_selected_data_y_size)
selected_modis_data = selected_modis_data.ravel()

CPU times: user 5.39 ms, sys: 2.26 ms, total: 7.65 ms
Wall time: 3.63 ms


In [26]:
%%time

path = 'data/images/low_resolution/test.img'
driver = modis_img.GetDriver()
x_size, y_size = modis_img.RasterXSize, modis_img.RasterYSize
img = driver.Create(path, x_size, y_size, 1, gdal.GDT_UInt16)
img.SetGeoTransform(modis_img.GetGeoTransform())
img.SetProjection(modis_img.GetProjection())
img.GetRasterBand(1).Fill(0)
band = img.GetRasterBand(1)
raster = np.zeros((y_size, x_size), dtype=np.uint16)
for y in range(modis_y_offset, modis_selected_data_x_size):
    for x in range(modis_x_offset, modis_selected_data_y_size):
        raster[y][x] = selected_modis_data[modis_selected_data_x_size * y + x]
band.WriteArray(raster)
img = band = None

CPU times: user 9.98 s, sys: 19.4 s, total: 29.4 s
Wall time: 31.2 s
